sudo: required
services:
    - docker

before_install:
    - docker build -t tariqbeans/docker-react -f Dockerfile.dev .

script:
    - docker container run -e CI=true tariqbeans/docker-react npm run test